StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5A60AE2B8D435CE9}" {
   Id "EL-Keybinds_Inventory_MoveQuantity"
   Target_en_us "Move stack"
   Target_de_de "Stapel verschieben"
   Modified 1516407434
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A5EA70E9C33566A}" {
   Id "EL-Keybinds_Inventory_PickUpQuantity"
   Target_en_us "Pick up stack"
   Target_de_de "Stapel aufsammeln"
   Modified 1516407428
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A628A92C80C8905}" {
   Id "EL-Keybinds_Inventory_QuickSplitQuantity"
   Target_en_us "Half stack"
   Target_de_de "Stapel halbieren"
   Modified 1516408899
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A628A92CC3D121C}" {
   Id "EL-Keybinds_Inventory_SplitQuantity"
   Target_en_us "Split stack"
   Target_de_de "Stapel aufteilen"
   Modified 1516408876
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A5EA70D1ADCCA9E}" {
   Id "EL-Keybinds_Title"
   Target_en_us "Everon Life"
   Modified 1516153387
   Author "Arkensor"
   LastChanged "Arkensor"
  }
 }
}