StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5A5EAC09A82CFF44}" {
   Id "AR-EL_Inventory_TransferStack"
   Target_en_us "Transfer stack"
   Target_de_de "Stapel übertragen"
   DevNote "Duplicate entry of EL-Keybinds_Inventory_TransferStack until https://feedback.bistudio.com/T167518 is fixed"
   Modified 1516155653
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A5EA70E9C33566A}" {
   Id "EL-Keybinds_Inventory_TransferStack"
   Target_en_us "Transfer stack"
   Target_de_de "Stapel übertragen"
   Modified 1516154105
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A5EA70D1ADCCA9E}" {
   Id "EL-Keybinds_Title"
   Target_en_us "Everon Life"
   Modified 1516153387
   Author "Arkensor"
   LastChanged "Arkensor"
  }
 }
}