StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5A60AE2B8D435CE9}" {
   Id "EL-Keybinds_Inventory_MoveStack"
   Target_en_us "Move stack"
   Target_de_de "Stapel verschieben"
   Modified 1516286250
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A5EA70E9C33566A}" {
   Id "EL-Keybinds_Inventory_PickUpStack"
   Target_en_us "Pick up stack"
   Target_de_de "Stapel aufsammeln"
   Modified 1516286197
   Author "Arkensor"
   LastChanged "Arkensor"
  }
  CustomStringTableItem "{5A5EA70D1ADCCA9E}" {
   Id "EL-Keybinds_Title"
   Target_en_us "Everon Life"
   Modified 1516153387
   Author "Arkensor"
   LastChanged "Arkensor"
  }
 }
}